# ===============================================================
# pubspec.yaml
# ---------------------------------------------------------------
# SHRD Mobile Application Configuration
#
# PURPOSE
# ---------------------------------------------------------------
# 1. Application information
# 2. Package dependencies
# 3. Development packages
# 4. Asset registration
# 5. App icon generation
# ===============================================================

name: shuttle_mobile_app

description: SHRD Shuttle Booking Mobile Application

publish_to: 'none'

version: 1.0.1+2

# ===============================================================
# Dart SDK Version
# ===============================================================

environment:
  sdk: ^3.12.1

# ===============================================================
# Application Dependencies
# ===============================================================

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # API Calls
  http: ^1.2.1

  # Local Storage
  shared_preferences: ^2.5.3

  razorpay_flutter: 1.4.1

#dependency_overrides:
#  fluttertoast: 8.2.12

# ===============================================================
# Development Dependencies
# ===============================================================

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # App Icon Generator
  flutter_launcher_icons: ^0.14.4

# ===============================================================
# Flutter Configuration
# ===============================================================

flutter:

  uses-material-design: true

  assets:

    - assets/images/

    - assets/icons/

# ===============================================================
# Application Icon Configuration
# ---------------------------------------------------------------
# Generates Android and iOS application icons
#
# REQUIRED FILE:
# assets/images/logo.jpeg
# ===============================================================

flutter_launcher_icons:

  android: true

  ios: true

  image_path: "assets/images/logo.jpeg"

  remove_alpha_ios: true